name: lint
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
          args:
            -v
            --max-same-issues 10
            --disable-all
            --exclude-use-default=false
            -E asciicheck
            -E deadcode
            -E errcheck
            -E forcetypeassert
            -E gocritic
            -E gofmt
            -E goimports
            -E gosimple
            -E govet
            -E ineffassign
            -E misspell
            -E revive
            -E staticcheck
            -E structcheck
            -E typecheck
            -E unused
            -E varcheck
